apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
            - name: hello
              image: appcron:latest
              imagePullPolicy: Never
              envFrom:
                - secretRef:
                    name: postgres-secret
              command: [ "sh","-c","./appCron $FLAG $TEXT" ]

              env:
                  - name: TEXT
                    value: "../../my_files"
                  - name: FLAG
                    value: "-c"

              volumeMounts:
                  - name: job-volume
                    mountPath: /my_files
          volumes:
                  - name: job-volume
                    persistentVolumeClaim:
                      claimName: my-persistent-volumeclaim
          restartPolicy: Never