apiVersion: v1
kind: Service
metadata:
  name: nginx-webapp-db
  labels:
    app: nginx-webapp
spec:
  ports:
    - name: postgres
      port: 5432

  selector:
    app: nginx-webapp
  type: NodePort

