apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: fullstack-postgres-new-svc1                         # Name of the resource
  labels:                                           # Labels that will be applied to the resource
    app: fullstack-postgres-new
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:                                         # Selects any Pod with labels `app=fullstack-postgres,tier=postgres`
    app: fullstack-postgres-new
    tier: postgres