apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  POSTGRES_USER: user
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: hashdb

  DB_HOST: fullstack-postgres-new-svc1
  DB_DRIVER: postgres
  API_SECRET: "98hbun98h"
  DB_USER: user
  DB_PASSWORD: "1234"
  DB_NAME: hashdb
  DB_PORT: "5432"
