apiVersion: apps/v1
kind: Deployment                                # Type of the kubernetes resource
metadata:
  name: fullstack-postgres-new-dep                      # Name of the deployment
  labels:                                        # Labels applied to this deployment 
    app: fullstack-postgres-new
spec:
  selector:
    matchLabels:                                  # This deployment applies to the Pods matching the specified labels
      app: fullstack-postgres-new
      tier: postgres
  replicas: 1
  template:                                       # Template for the Pods in this deployment
    metadata:
      labels:                                     # Labels to be applied to the Pods in this deployment
        app: fullstack-postgres-new
        tier: postgres
    spec:                                         # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: postgres:10                 # The container image
          name: postgres
          imagePullPolicy: "IfNotPresent"
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh","-c","sleep 20 && PGPASSWORD=$POSTGRES_PASSWORD psql -w -d $POSTGRES_DB -U $POSTGRES_USER -c 'CREATE TABLE IF NOT EXISTS hashfiles ( id           BIGSERIAL PRIMARY KEY,fileName     VARCHAR NOT NULL,fullFilePath TEXT    NOT NULL,algorithm    VARCHAR NOT NULL, hashSum      VARCHAR NOT NULL, deleted      BOOLEAN DEFAULT false);'" ]

          envFrom:                                # Get the environmental variables from a secret file whose name is "postgres-secret"
            - secretRef:
                name: postgres-secret
            
          ports:
            - containerPort: 5432                   # The port that the container exposes 
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage     # This name should match the name specified in `volumes.name`
      volumes:                                      # A PersistentVolume is mounted as a volume to the Pod 
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim



